language: java
jdk:
  - oraclejdk8
  - oraclejdk9
install: 
  - sh -c 'cd jOOR && mvn install -DskipTests=true'
  - sh -c 'cd jOOR-java-6 && mvn install -DskipTests=true'
script: 
  - sh -c 'cd jOOR && mvn test'
  - sh -c 'cd jOOR-java-6 && mvn test'
